version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: chatapp-mongo
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: chatapp-backend
    # restart: always
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/usr/src/app

volumes:
  mongo_data:
